# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'officer.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Source,sys
from datetime import datetime#tocopy

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        # localtime = time.asctime( time.localtime(time.time()) )
        # now = datetime.now()
        timer = QtCore.QTimer(Dialog)#tocopy
        timer.timeout.connect(lambda: self.retranslateUi(Dialog))#tocopy
        timer.start(1000)#tocopy
        # localtime = now.strftime("%H:%M:%S")
        Dialog.setObjectName("Dialog")
        Dialog.resize(1400, 800)
        Dialog.setStyleSheet("background: #FFFFFF;\n"
"")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1401, 80))
        self.frame.setStyleSheet("position: absolute;\n"
"background: #7879FF;\n"
"border-radius: 0px 0px 25px 25px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(43, 29, 140, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: #F80000;\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(1230, 30, 140, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: #0000;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame)
        self.pushButton_3.setGeometry(QtCore.QRect(690, 20, 221, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("color: #FFFFFF;\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(266, 243, 330, 350))
        self.frame_2.setStyleSheet("position: absolute;\n"
"width: 330px;\n"
"height: 350px;\n"
"\n"
"background: #7879FF;\n"
"border-radius: 25px;\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(60, 60, 183, 180))
        self.label_2.setStyleSheet("image: url(:/all/PENDING.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(60, 270, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #FFFFFF;")
        self.label_4.setObjectName("label_4")
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setGeometry(QtCore.QRect(804, 243, 330, 350))
        self.frame_3.setStyleSheet("position: absolute;\n"
"width: 330px;\n"
"height: 350px;\n"
"\n"
"background: #7879FF;\n"
"border-radius: 25px;\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(80, 50, 183, 180))
        self.label.setStyleSheet("image: url(:/all/ALLCASES.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(70, 60, 183, 180))
        self.label_3.setStyleSheet("image: url(:/all/ALLCASES.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(110, 260, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: #FFFFFF;")
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        #while(True):self.pushButton_2.setText(localtime)
    def retranslateUi(self, Dialog):
        now = datetime.now()#tocopy
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "LOGOUT"))
        self.pushButton_2.setText(_translate("Dialog", now.strftime("%H:%M:%S"))) #tocopy
        self.pushButton_3.setText(_translate("Dialog", "OFFICER"))
        self.label_4.setText(_translate("Dialog", "Pending Cases"))
        self.label_5.setText(_translate("Dialog", "All Cases"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
