# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pendingcases.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from datetime import datetime#tocopy

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        timer = QtCore.QTimer(Dialog)#tocopy
        timer.timeout.connect(lambda: self.retranslateUi(Dialog))#tocopy
        timer.start(1000)#tocopy    
        Dialog.setObjectName("Dialog")
        Dialog.resize(1400, 800)
        Dialog.setStyleSheet("background: #FFFFFF;\n"
"\n"
"")
        self.topheader = QtWidgets.QFrame(Dialog)
        self.topheader.setGeometry(QtCore.QRect(0, 0, 1401, 80))
        self.topheader.setStyleSheet("position: absolute;\n"
"background: #7879FF;\n"
"border-radius: 0px 0px 25px 25px;\n"
"")
        self.topheader.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topheader.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topheader.setObjectName("topheader")
        self.btnlogout = QtWidgets.QPushButton(self.topheader)
        self.btnlogout.setGeometry(QtCore.QRect(43, 29, 140, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnlogout.setFont(font)
        self.btnlogout.setStyleSheet("color: #F80000;\n"
"")
        self.btnlogout.setObjectName("btnlogout")
        self.pushButton_2 = QtWidgets.QPushButton(self.topheader)
        self.pushButton_2.setGeometry(QtCore.QRect(1230, 30, 140, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: #0000;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.topheader)
        self.label_4.setGeometry(QtCore.QRect(560, 10, 381, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #FFFFFF;\n"
"\n"
"")
        self.label_4.setObjectName("label_4")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(130, 130, 1131, 561))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)

        self.tableWidget.setColumnWidth(0, 187)
        self.tableWidget.setColumnWidth(1, 187)
        self.tableWidget.setColumnWidth(2, 187)
        self.tableWidget.setColumnWidth(3, 188)
        self.tableWidget.setColumnWidth(4, 190)
        self.tableWidget.setColumnWidth(5, 190)
        
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        now = datetime.now()#tocopy
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnlogout.setText(_translate("Dialog", "Back"))
        self.pushButton_2.setText(_translate("Dialog", now.strftime("%H:%M:%S"))) #tocopy
        self.label_4.setText(_translate("Dialog", "Pending Cases"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Crime Date "))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Crime Time "))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Crime Type "))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Location"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Gender"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
