# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'allcases.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from datetime import datetime#tocopy
from PyQt5.QtWidgets import QTableWidgetItem, QMessageBox
import mysql.connector as mc
import mysql_comn


class Ui_pnl_user(object):
    def setupUi(self, pnl_user):
        timer = QtCore.QTimer(pnl_user)#tocopy
        timer.timeout.connect(lambda: self.retranslateUi(pnl_user))#tocopy
        timer.start(1000)#tocopy  
        pnl_user.setObjectName("pnl_user")
        pnl_user.resize(1400, 800)
        pnl_user.setStyleSheet("background: #FFFFFF;\n"
"")
        self.topheader = QtWidgets.QFrame(pnl_user)
        self.topheader.setGeometry(QtCore.QRect(0, 0, 1401, 80))
        self.topheader.setStyleSheet("position: absolute;\n"
"background: #7879FF;\n"
"border-radius: 0px 0px 25px 25px;\n"
"")
        self.topheader.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topheader.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topheader.setObjectName("topheader")
        self.btnlogout = QtWidgets.QPushButton(self.topheader)
        self.btnlogout.setGeometry(QtCore.QRect(43, 29, 140, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btnlogout.setFont(font)
        self.btnlogout.setStyleSheet("color: #F80000;\n"
"")
        self.btnlogout.setObjectName("btnlogout")
        self.pushButton_2 = QtWidgets.QPushButton(self.topheader)
        self.pushButton_2.setGeometry(QtCore.QRect(1230, 30, 140, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: #0000;\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.topheader)
        self.label_4.setGeometry(QtCore.QRect(620, 10, 261, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #FFFFFF;\n"
"\n"
"")
        self.label_4.setObjectName("label_4")
        self.tableWidget = QtWidgets.QTableWidget(pnl_user)
        self.tableWidget.setGeometry(QtCore.QRect(130, 160, 1131, 561))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)

        self.tableWidget.setColumnWidth(0, 187)
        self.tableWidget.setColumnWidth(1, 187)
        self.tableWidget.setColumnWidth(2, 187)
        self.tableWidget.setColumnWidth(3, 188)
        self.tableWidget.setColumnWidth(4, 190)
        self.tableWidget.setColumnWidth(5, 190)
        
        self.comboBox = QtWidgets.QComboBox(pnl_user)
        self.comboBox.setGeometry(QtCore.QRect(1030, 110, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(pnl_user)
        self.select_data()
        QtCore.QMetaObject.connectSlotsByName(pnl_user)
        

    def retranslateUi(self, pnl_user):
        now = datetime.now()#tocopy
        _translate = QtCore.QCoreApplication.translate
        pnl_user.setWindowTitle(_translate("pnl_user", "Dialog"))
        self.btnlogout.setText(_translate("pnl_user", "Back"))
        self.pushButton_2.setText(_translate("pnl_user", now.strftime("%H:%M:%S"))) #tocopy
        self.label_4.setText(_translate("pnl_user", "All Cases"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("pnl_user", "Crime Date "))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("pnl_user", "Crime Time "))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("pnl_user", "Crime Type "))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("pnl_user", "Location"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("pnl_user", "Gender"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("pnl_user", "Status"))
        self.comboBox.setItemText(0, _translate("pnl_user", "All"))
        self.comboBox.setItemText(1, _translate("pnl_user", "Approved"))
        self.comboBox.setItemText(2, _translate("pnl_user", "Rejected"))
        self.comboBox.setItemText(3, _translate("pnl_user", "Pending"))


    def select_data(self):
        try:
            mydb = mysql_comn.mydb
            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM crimereport")

            result = mycursor.fetchall()

            self.tableWidget.setRowCount(0)

            for row_number, row_data in enumerate(result):
                uDate = row_data[2]
                uTime = row_data[3]
                uType = row_data[4]
                uLocation = row_data[6]
                uGender = row_data[7]
                

                self.tableWidget.insertRow(row_number)

                self.tableWidget.setItem(row_number, 0, QTableWidgetItem(str(uDate)))
                self.tableWidget.setItem(row_number, 1, QTableWidgetItem(str(uTime)))
                self.tableWidget.setItem(row_number, 2, QTableWidgetItem(str(uType)))
                self.tableWidget.setItem(row_number, 3, QTableWidgetItem(str(uLocation)))
                self.tableWidget.setItem(row_number, 4, QTableWidgetItem(str(uGender)))
                
               # self.tableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)

        except mc.Error as e:
            #print("Error occured")
            msg = QMessageBox()
            msg.setWindowTitle("Error occured")
            msg.setText("Error occured")
            x = msg.exec_()
 

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pnl_user = QtWidgets.QDialog()
    ui = Ui_pnl_user()
    ui.setupUi(pnl_user)
    pnl_user.show()
    sys.exit(app.exec_())
