# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userlist.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc
from PyQt5.QtWidgets import QTableWidgetItem, QMessageBox
import mysql_comn



class Ui_Userlist(object):
    def setupUi(self, Userlist):
        Userlist.setObjectName("Userlist")
        Userlist.resize(1400, 800)
        Userlist.setStyleSheet("background: #FFFFFF;\n"
                               "")
        self.frame = QtWidgets.QFrame(Userlist)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1401, 80))
        self.frame.setStyleSheet("position: absolute;\n"
                                 "background: #7879FF;\n"
                                 "border-radius: 0px 0px 25px 25px;\n"
                                 "")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.Btn_back = QtWidgets.QPushButton(self.frame)
        self.Btn_back.setGeometry(QtCore.QRect(43, 29, 140, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Btn_back.setFont(font)
        self.Btn_back.setStyleSheet("color: #F80000;\n"
                                    "")
        self.Btn_back.setObjectName("Btn_back")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(1230, 30, 140, 35))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: #0000;\n"
                                        "")
        self.pushButton_2.setObjectName("pushButton_2")
        self.Label_user = QtWidgets.QPushButton(self.frame)
        self.Label_user.setGeometry(QtCore.QRect(600, 20, 311, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.Label_user.setFont(font)
        self.Label_user.setStyleSheet("color: #FFFFFF;\n"
                                      "")
        self.Label_user.setObjectName("Label_user")
        self.txt_searchbar = QtWidgets.QTextEdit(Userlist)
        self.txt_searchbar.setGeometry(QtCore.QRect(960, 100, 191, 31))
        self.txt_searchbar.setObjectName("txt_searchbar")
        self.btn_search = QtWidgets.QPushButton(Userlist)
        self.btn_search.setGeometry(QtCore.QRect(1170, 102, 93, 28))
        self.btn_search.setObjectName("btn_search")
        self.tableWidget = QtWidgets.QTableWidget(Userlist)
        self.tableWidget.setGeometry(QtCore.QRect(230, 170, 941, 521))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)

        self.tableWidget.setColumnWidth(0, 235)
        self.tableWidget.setColumnWidth(1, 232)
        self.tableWidget.setColumnWidth(2, 230)
        self.tableWidget.setColumnWidth(3, 240)
        self.tableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)



        self.retranslateUi(Userlist)
        self.select_data()
        QtCore.QMetaObject.connectSlotsByName(Userlist)

    def retranslateUi(self, Userlist):
        _translate = QtCore.QCoreApplication.translate
        Userlist.setWindowTitle(_translate("Userlist", "Dialog"))
        self.Btn_back.setText(_translate("Userlist", "Back"))
        self.pushButton_2.setText(_translate("Userlist", "TIME"))
        self.Label_user.setText(_translate("Userlist", "Users"))
        self.btn_search.setText(_translate("Userlist", "Search"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Userlist", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Userlist", "Username"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Userlist", "Mobile No."))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Userlist", "Email Id"))

    def select_data(self):
        try:
            mydb = mysql_comn.mydb

            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM acc")

            result = mycursor.fetchall()

            self.tableWidget.setRowCount(0)

            for row_number, row_data in enumerate(result):
                uName = row_data[2]
                uUserName = row_data[1]
                uMob = row_data[5]
                uEmail = row_data[4]

                self.tableWidget.insertRow(row_number)

                self.tableWidget.setItem(row_number, 0, QTableWidgetItem(str(uName)))
                self.tableWidget.setItem(row_number, 1, QTableWidgetItem(str(uUserName)))
                self.tableWidget.setItem(row_number, 2, QTableWidgetItem(str(uMob)))
                self.tableWidget.setItem(row_number, 3, QTableWidgetItem(str(uEmail)))
               # self.tableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)

        except mc.Error as e:
            #print("Error occured")
            msg = QMessageBox()
            msg.setWindowTitle("Error occured")
            msg.setText("Error occured")
            x = msg.exec_()

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Userlist = QtWidgets.QDialog()
    ui = Ui_Userlist()
    ui.setupUi(Userlist)
    Userlist.show()
    sys.exit(app.exec_())

    #RUN KAR
