# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewrep.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from audioop import add
from datetime import datetime
from PyQt5 import QtCore, QtGui, QtWidgets
# from PyQt5.QtCore import QString
import sys
import os
from mysql_comn import mydb
from mysql.connector import Error

class Ui_ReportForm(object):


        def setupUi(self, ReportForm):
                self.currentCrimeID = 5
                ReportForm.setObjectName("ReportForm")
                print("from view page: " , self.currentCrimeID)
                ReportForm.resize(1406, 800)
                self.frame = QtWidgets.QFrame(ReportForm)
                self.frame.setGeometry(QtCore.QRect(10, 0, 1401, 80))
                self.frame.setStyleSheet("position: absolute;\n"
                "background: #7879FF;\n"
                "border-radius: 0px 0px 25px 25px;\n"
                "")
                self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
                self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
                self.frame.setObjectName("frame")
                self.pushButton_2 = QtWidgets.QPushButton(self.frame)
                self.pushButton_2.setGeometry(QtCore.QRect(1230, 30, 140, 35))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(20)
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_2.setFont(font)
                self.pushButton_2.setStyleSheet("color: #0000;\n"
                "")
                self.pushButton_2.setObjectName("pushButton_2")
                self.viewreport_title = QtWidgets.QPushButton(self.frame)
                self.viewreport_title.setGeometry(QtCore.QRect(510, 20, 451, 50))
                font = QtGui.QFont()
                font.setFamily("Arial")
                font.setPointSize(30)
                font.setBold(True)
                font.setWeight(75)
                self.viewreport_title.setFont(font)
                self.viewreport_title.setStyleSheet("color: #FFFFFF;\n"
                "")
                self.viewreport_title.setObjectName("viewreport_title")
                self.crimedetails_label = QtWidgets.QLabel(ReportForm)
                self.crimedetails_label.setGeometry(QtCore.QRect(510, 100, 191, 31))
                self.crimedetails_label.setObjectName("crimedetails_label")
                self.date_label = QtWidgets.QLabel(ReportForm)
                self.date_label.setGeometry(QtCore.QRect(70, 200, 111, 51))
                self.date_label.setObjectName("date_label")
                self.time_label = QtWidgets.QLabel(ReportForm)
                self.time_label.setGeometry(QtCore.QRect(70, 260, 111, 51))
                self.time_label.setObjectName("time_label")
                self.type_label = QtWidgets.QLabel(ReportForm)
                self.type_label.setGeometry(QtCore.QRect(60, 320, 121, 51))
                self.type_label.setObjectName("type_label")
                self.overview_label = QtWidgets.QLabel(ReportForm)
                self.overview_label.setGeometry(QtCore.QRect(60, 380, 161, 51))
                self.overview_label.setObjectName("overview_label")
                self.location_label = QtWidgets.QLabel(ReportForm)
                self.location_label.setGeometry(QtCore.QRect(870, 190, 161, 51))
                self.location_label.setObjectName("location_label")
                self.gender_label = QtWidgets.QLabel(ReportForm)
                self.gender_label.setGeometry(QtCore.QRect(860, 250, 161, 51))
                self.gender_label.setObjectName("gender_label")
                self.overview_label_4 = QtWidgets.QLabel(ReportForm)
                self.overview_label_4.setGeometry(QtCore.QRect(880, 310, 161, 51))
                self.overview_label_4.setObjectName("overview_label_4")
                self.crimedetails_label_2 = QtWidgets.QLabel(ReportForm)
                self.crimedetails_label_2.setGeometry(QtCore.QRect(510, 440, 241, 31))
                self.crimedetails_label_2.setObjectName("crimedetails_label_2")
                self.adhaar_label = QtWidgets.QLabel(ReportForm)
                self.adhaar_label.setGeometry(QtCore.QRect(70, 500, 151, 51))
                self.adhaar_label.setObjectName("adhaar_label")
                self.fullname_label = QtWidgets.QLabel(ReportForm)
                self.fullname_label.setGeometry(QtCore.QRect(50, 560, 151, 51))
                self.fullname_label.setObjectName("fullname_label")
                self.email_label = QtWidgets.QLabel(ReportForm)
                self.email_label.setGeometry(QtCore.QRect(40, 620, 151, 51))
                self.email_label.setObjectName("email_label")
                self.status_label = QtWidgets.QLabel(ReportForm)
                self.status_label.setGeometry(QtCore.QRect(30, 680, 151, 51))
                self.status_label.setObjectName("status_label")
                self.mobile_label = QtWidgets.QLabel(ReportForm)
                self.mobile_label.setGeometry(QtCore.QRect(860, 550, 151, 51))
                self.mobile_label.setObjectName("mobile_label")
                self.address_label = QtWidgets.QLabel(ReportForm)
                self.address_label.setGeometry(QtCore.QRect(850, 620, 151, 51))
                self.address_label.setObjectName("address_label")
                self.username_label = QtWidgets.QLabel(ReportForm)
                self.username_label.setGeometry(QtCore.QRect(860, 480, 151, 51))
                self.username_label.setObjectName("username_label")
                self.comboBox = QtWidgets.QComboBox(ReportForm)
                self.comboBox.setGeometry(QtCore.QRect(450, 680, 161, 34))
                self.comboBox.setStyleSheet("background: #7879FF;")
                self.comboBox.setObjectName("comboBox")
                self.comboBox.addItem("")
                self.comboBox.addItem("")
                self.comboBox.addItem("")
                self.ok_pushbutton = QtWidgets.QPushButton(ReportForm)
                # 680 change by x
                self.ok_pushbutton.setGeometry(QtCore.QRect(760, 680, 91, 41))
                self.ok_pushbutton.setStyleSheet("background: #55aaff")
                self.ok_pushbutton.setObjectName("ok_pushbutton")

                self.retranslateUi(ReportForm)
                #self.select_data()
                QtCore.QMetaObject.connectSlotsByName(ReportForm)
                self.mysql_get()

        def retranslateUi(self, ReportForm):
                _translate = QtCore.QCoreApplication.translate
                ReportForm.setWindowTitle(_translate("ReportForm", "Form"))
                self.pushButton_2.setText(_translate("ReportForm", "TIME"))
                self.viewreport_title.setText(_translate("ReportForm", "VIEW REPORT"))
                self.crimedetails_label.setText(_translate("ReportForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Crime Details</span></p></body></html>"))
                self.date_label.setText(_translate("ReportForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Crime Date:</span></p></body></html>"))
                self.time_label.setText(_translate("ReportForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Crime Time:</span></p></body></html>"))
                self.type_label.setText(_translate("ReportForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Crime Type:</span></p></body></html>"))
                self.overview_label.setText(_translate("ReportForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Crime Overview:</span></p></body></html>"))
                self.location_label.setText(_translate("ReportForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Location:</span></p></body></html>"))
                self.gender_label.setText(_translate("ReportForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Gender:</span></p></body></html>"))
                self.overview_label_4.setText(_translate("ReportForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Description:</span></p></body></html>"))
                self.crimedetails_label_2.setText(_translate("ReportForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Reporter Details</span></p></body></html>"))
                self.adhaar_label.setText(_translate("ReportForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Adhaar Card No:</span></p></body></html>"))
                self.fullname_label.setText(_translate("ReportForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Full Name:</span></p></body></html>"))
                self.email_label.setText(_translate("ReportForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Email Id:</span></p></body></html>"))
                self.status_label.setText(_translate("ReportForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Status:</span></p></body></html>"))
                self.mobile_label.setText(_translate("ReportForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Mobile No:</span></p></body></html>"))
                self.address_label.setText(_translate("ReportForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Address:</span></p></body></html>"))
                self.username_label.setText(_translate("ReportForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Username:</span></p></body></html>"))
                self.comboBox.setItemText(0, _translate("ReportForm", "Pending"))
                self.comboBox.setItemText(1, _translate("ReportForm", "Approve"))
                self.comboBox.setItemText(2, _translate("ReportForm", "Reject"))
                self.ok_pushbutton.setText(_translate("ReportForm", "OK"))



                # self.tableWidget.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        
        def mysql_get(self):
                mycursor = mydb.cursor()
                try:
                        sql_query = "SELECT a.full_name, a.E_mail, a.username, a.mobile_no , a.add , b.Date, b.Time, b.Overview, b.Gender, b.Description, b.Type, b.Location  from acc as a INNER JOIN crimereport as b ON a.`Srno.` = b.`P_id`  where b.id = '%s'"
                        mycursor.execute( "SELECT a.full_name, a.E_mail, a.username, a.mobile_no , a.add , b.Date, b.Time, b.Overview, b.Gender, b.Description, b.Type, b.Location  from acc as a INNER JOIN crimereport as b ON a.`Srno.` = b.`P_id`  where b.id = '1' ")
                        result = mycursor.fetchall()
                        array = [self.date_label, self.time_label,  self.type_label , self.overview_label, self.adhaar_label, self.fullname_label, self.email_label , self.status_label, self.mobile_label, self.address_label, self.username_label, self.gender_label, self.location_label, self.overview_label_4]
                        for row_number, row_data in enumerate(result):
                                print(row_data[2])
                                fullname = row_data[0]
                                email = row_data[1]
                                username = row_data[2]
                                mobileno = row_data[3]
                                address = row_data[4]
                                date = row_data[5]
                                time = row_data[6]
                                overview = row_data[7]
                                gender = row_data[8]
                                description = row_data[9]
                                type_crime = row_data[10]
                                location = row_data[11]
                                print("date")
                except Error as err:
                        print(err)
                array_val = [date, time, type_crime, overview, "adhar no", fullname, email, "false", mobileno, address, username, gender, location, description]
                array_label = ["date", "time", "type_crime", "overview", "adhar no", "fullname", "email", "false", "mobileno", "address", "username", "gender", "location", "description"]

                for i in range(len(array)):
                        labelText = array_label[i] 
                        labelText += "  : "  + str(array_val[i])

                        array[i].setText( labelText )
                        # array[i].setText( labelText )
                        # pass
      
if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        Dialog = QtWidgets.QWidget()
        ui = Ui_ReportForm()
        ui.setupUi(Dialog)
        Dialog.show()
        sys.exit(app.exec_())

